// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// point_reduce
List point_reduce(NumericVector vec, double tolerance = .01);
RcppExport SEXP timeseriesr_point_reduce(SEXP vecSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type vec(vecSEXP );
        Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP );
        List __result = point_reduce(vec, tolerance);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// vdeduplicate
NumericVector vdeduplicate(NumericVector x, bool returnIndex = false);
RcppExport SEXP timeseriesr_vdeduplicate(SEXP xSEXP, SEXP returnIndexSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP );
        Rcpp::traits::input_parameter< bool >::type returnIndex(returnIndexSEXP );
        NumericVector __result = vdeduplicate(x, returnIndex);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
